const actionVariables = {
  ONOSCHAMPIONCLICK: "ONOSCHAMPIONCLICK",
  ONUSCHAMPIONCLICK: "ONUSCHAMPIONCLICK",
  ONCSCHAMPIONCLICK: "ONUSCHAMPIONCLICK",
  ONSEARCHTERMCHANGE: "ONSEARCHTERMCHANGE"
};

export default actionVariables;
