const actionVariables = {
  ONOSCHAMPIONCLICK: "ONOSCHAMPIONCLICK",
  ONUSCHAMPIONCLICK: "ONUSCHAMPIONCLICK",
  ONCSCHAMPIONCLICK: "ONCSCHAMPIONCLICK",
  ONSEARCHTERMCHANGE: "ONSEARCHTERMCHANGE",
  ONCLICKEDLANE: "ONCLICKEDLANE",
  ONLOGIN: "ONLOGIN",
  ONLOGOUT: "ONLOGOUT",
  ONSIGNUP: "ONSIGNUP",
  ONFINDMATCHCLICK: "ONFINDMATCHCLICK",
  ONCHANGELANE: "ONCHANGELANE",
  ONCHANGEMENUVIEW: "ONCHANGEMENUVIEW"
};

export default actionVariables;
